import numpy as np
a=np.array([10,20,30])
b=np.array([1,2,3])
print("Array A:",a)
print("Array B:",b)
print("\nAddition:")
print(a+b)
print("\nsubtraction:")
print(a-b)
print("\nmultiplication:")
print(a*b)
print("\ndivision:")
print(a/b)
print("\npower:")
print(a**2)