import numpy as np
zeros=np.zeros(5)
ones=np.ones(5)
numbers=np.arange(1,11)
values=np.linspace(0,10,6)
print("zeros:")
print(zeros)
print("\nones:")
print("ones")
print("\nNumbers from 1 to 10:")
print(numbers)
print("\nSix equally spaced from 0 to 10:")
print(values)